// <auto-generated />
namespace Monotoring.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig1205 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig1205));
        
        string IMigrationMetadata.Id
        {
            get { return "201705122251247_mig1205"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
